name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo "Current PATH: $PATH"
            echo "PNPM Path: $(which pnpm)"
            echo "PM2 Path: $(which pm2)"
            cd ~/Projects/faculty-news-telegram-bot
            git pull
            pnpm install
            pnpm build
            pm2 restart faculty-bot
